services:
  - type: web
    name: nodejs-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: postgres-db
    databaseName: mydb
    user: myuser
    plan: free
