services:
  - type: web
    name: nodejs-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js  
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: NODE_ENV
        value: production